### PR TITLE
Added increment and decrement instance methods

### PR DESCRIPTION
**Pull request by gilest**
Not sure if anyone else will find this useful but thought it would be worth sharing in just in case.

Behaviour of these methods is almost equivalent to those in `ActiveRecord::Persistence`.

### CODE REVIEW

**Comment by ramontayag** [comment]
@gilest thanks for the PR! I think storext should make it feel, as much as possible, like you're just working with plain database fields. I'm leaning towards monkey-patching `increment` and `decrement` instead. That way, you won't have to call a separate `storext_(increment|decrement)` method. It doesn't seem there's any drawback here if monkey-patched properly. Would you be willing to do this?

**Comment by gilest** [comment]
Hey @ramontayag 

I wondered about doing this myself, but wasn't keen on adding an ActiveRecord monkey-patch in our own project's code. I'd be comfortable doing it within the gem if it's well tested.

````ruby
if self.class.column_names.include?(attribute)
    increment!(attribute)
  elsif storext_has_key?(:data, attribute)
    storext_increment!(attribute
  end
```

I'll see if I can find some time to have a go at it soon.

**Comment by ramontayag** [comment]
Yes that looks like a good way to go. And I think you're right in not adding it to your own project.

I know the old way was to use `alias_method_chain`. I am not very familiar with the newer, recommended way: `Module#prepend`. See https://github.com/rails/rails/pull/19434.

**Comment by gilest** [comment]
I've used `Module#prepend` before. Should be pretty easy to suss.

**Comment by ramontayag** [comment]
Great. Thanks, @gilest. Let me know if you need assistance.

**Comment by ramontayag** [comment]
@gilest you probably got busy, so I'll close this. Feel free to re-open when ready.

**Pull request closed without merging**
